### ISSUE TITLE
Will there be JPMS support?

### ISSUE THREAD

**Issue by fwgreen** [dinject/dinject#15]
While there is some overlap, there also seems to be places where DI could make JPMS easier to live with.  Is there a plan to add JPMS support?  Here's an example of the [Dagger Coffee App](https://github.com/fwgreen/CoffeeApp) using modules.  It works, but DI would definitely make it more elegant.

**Comment by rbygrave** [comment]
> plan to add JPMS support?

JPMS in this sense to me just means ServiceLoader and `modules provides`.  Do you have a different view on what it means?

In terms of ServiceLoader, it's great but limited and (irrespective of DInject) when we use ServiceLoader we need to additionally code `scope` for ServiceLoader to be something like:
- singleton on first instance and we expect only 1 instance (reuse the same instance as needed)
- create new each time and expect only 1 instance (prototype scope)
- create new expecting many instances (all implementations of ...)

So when this is sufficient and good then ServiceLoader is nice. 
Is this DI though?  Not so much and we can see that code like:

```java
    static Heater getInstance() {
        return ServiceLoader.load(Heater.class).findFirst().get();
    }
```

```java
    private final Heater heater;
    private final Pump pump;

    public CoffeeMaker() {
        this.heater = Heater.getInstance();
        this.pump =  Pump.getInstance();
    }
```

So, can we use DI within the scope of a single module? Yes, I have thoughts and plans for this.  This means DInject is used totally internally inside a module and the outside world just sees something provided by ServiceLoader (often exposed with singleton scope - maybe via default method on interface).

Can we use DI across JPMS modules?  Well, to call it DI and have it look like DI in code terms I think we need to expose the context (BuilderContext) such that we actually get things like constructor injection done for us (by DInject).  Could this be done?  Yes, but we are pretty much have to avoid the "everything is exposed as ServiceLoader" approach and this means that it then works pretty much the same in non-JPMS world (but with improved package visibility rules).

What is your view of it?

**Comment by fwgreen** [comment]
I think we're of one mind as how I see DInject working with JPMS.  Thanks for taking the time to highlight the other areas where ServiceLoader is deficient in a DI context; I have much to learn:  My primary gripe was the lack of a singleton instance and I did not delve any further.

**Comment by rbygrave** [comment]
I've put up a version of the CoffeeApp example using DInject: https://github.com/dinject/CoffeeApp

Note that this doesn't use java module-info / module system etc.  

You could try and adjust it - for me it was not obvious how to get the annotation processing working and I've got a few other things to sort out etc so I need to look at those things.

**Comment by rbygrave** [comment]
I'll close this for now.
