### ISSUE TITLE
Feature: @Transactional

### ISSUE THREAD

**Issue by yaskor** [dinject/dinject#17]
First of all, great library.
Only thing missing (for me) is @Transactional.
One could define a DataSource and a TransactionManager and dinject would inject the transaction code into the annotated methods.

I have allready written something with an functional aproch like:

```
transactionManager.doInTransaction(()->{
    foo1();
    foo2();
})
```

But a annotation would be much nicer...

**Comment by rbygrave** [comment]
Yes there are roughly 2 things I see missing:
1)  `@Transational` 
2)  Configuration / replacement for `@Value`

I personally use Ebean ORM  (https://ebean.io) that has `@Transactional` built in so adding some generic AOP support that would include `@Transactional` could be done but personally isn't a priority yet.

**Comment by rbygrave** [comment]
I'll close this.
