### ISSUE TITLE
@Factory fails with types implementing interfaces

### ISSUE THREAD

**Issue by nschlehe** [dinject/dinject#19]
When using factory with beans implementing interfaces the generated class is missing imports for those interfaces.
In this example imports for Versioned and Serializable are missing.

I tried fixing it myself but didn't find a quick way how to debug apt processors. If you can provide me a hint about your development setup for dinject I would be happy fixing this myself.

```kotlin
package de.testung.example

import com.fasterxml.jackson.databind.ObjectMapper
import io.dinject.Bean
import io.dinject.Factory

@Factory
class ObjectMapperFactory {
    @Bean
    fun createObjectMapper(): ObjectMapper {
        return ObjectMapper()
    }
}
```
Generated class:

```java
package de.testung.example;

import com.fasterxml.jackson.databind.ObjectMapper;
import de.testung.example.ObjectMapperFactory;
import io.dinject.core.Builder;
import javax.annotation.Generated;

@Generated("io.dinject.generator")
public class ObjectMapperFactory$di  {

  public static void build(Builder builder) {
    if (builder.isAddBeanFor(ObjectMapperFactory.class)) {
      ObjectMapperFactory bean = new ObjectMapperFactory();
      builder.register(bean, null);
    }
  }

  public static void build_createObjectMapper(Builder builder) {
    if (builder.isAddBeanFor(ObjectMapper.class)) {
      ObjectMapperFactory factory = builder.get(ObjectMapperFactory.class);
      ObjectMapper bean = factory.createObjectMapper();
      builder.register(bean, null, Versioned.class, Serializable.class);
    }
  }
}
```

**Comment by rbygrave** [comment]
Ok. I haven't reproduced this yet in either java or kotlin.  I'll try again maybe tomorrow night, not sure where the kotlin ObjectMapperFactory above has those interfaces - my kotlin code needed explicit interfaces.

**Comment by yaskor** [comment]
I am having the same Problem.

In this example imports for Database is missing.
`
package de.sample.javalin.config;

import com.zaxxer.hikari.HikariDataSource;
import io.dinject.Bean;
import io.dinject.Factory;
import io.ebean.EbeanServer;
import io.ebean.EbeanServerFactory;
import io.ebean.config.MatchingNamingConvention;
import io.ebean.config.ServerConfig;

@Factory
public class BeanFactory {

    @Bean
    public EbeanServer ebeanServer() {
        String test = "...";
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setDriverClassName(com.mysql.cj.jdbc.Driver.class.getName());
        dataSource.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
        dataSource.addDataSourceProperty("prepStmtCacheSize", "250");
        dataSource.addDataSourceProperty("cachePrepStmts", "true");
        dataSource.setJdbcUrl(test);
        dataSource.setMaximumPoolSize(26);

        ServerConfig config = new ServerConfig();
        config.setNamingConvention(new MatchingNamingConvention());
        config.setDataSource(dataSource);
        config.setDisableLazyLoading(true);
        return EbeanServerFactory.create(config);
    }
}
`

`
package de.sample.javalin.config;

import de.sample.javalin.config.BeanFactory;
import io.dinject.core.Builder;
import io.ebean.EbeanServer;
import javax.annotation.Generated;

@Generated("io.dinject.generator")
public class BeanFactory$di  {

  public static void build(Builder builder) {
    if (builder.isAddBeanFor(BeanFactory.class)) {
      BeanFactory bean = new BeanFactory();
      builder.register(bean, null);
    }
  }

  public static void build_ebeanServer(Builder builder) {
    if (builder.isAddBeanFor(EbeanServer.class)) {
      BeanFactory factory = builder.get(BeanFactory.class);
      EbeanServer bean = factory.ebeanServer();
      builder.register(bean, null, EbeanServer.class, Database.class);
    }
  }

}
`

**Comment by rbygrave** [comment]
Right .. I should be able to reproduce that.  I'll look to try and do that over the next few days.  
Thanks !!
