### ISSUE TITLE
Ignore lombok annotations (for bean classification) @Slf4j, @Getter, @Setter, @EqualsAndHashCode, @ToString

### ISSUE THREAD

**Issue by rbygrave** [dinject/dinject#28]

**Comment by aletundo** [comment]
Hi @rbygrave!

First, thanks for your amazing project, a really good one paried with Javalin.

I'm facing an issue which I guess may be related to this. At runtime, I got:
```
Exception in thread "main" java.lang.NoClassDefFoundError: lombok/Data
...
Caused by: java.lang.ClassNotFoundException: lombok.Data
```

Lombok: 1.18.12
Javalin: 3.9.1
Dinject: 1.18

```
@Singleton
@Data
public class RedisConfig {
  private static final Dotenv dotenv = Dotenv.load();
  private final String host;
  private final int port;
  private final String password;
  private final String uri;

  public RedisConfig() {
    this.host = dotenv.get("REDIS_HOST", "localhost");
    this.port = Integer.parseInt(dotenv.get("REDIS_PORT", "6379"));
    this.password = dotenv.get("REDIS_PASSWORD", "");
    this.uri = String.format("redis://%s@%s:%s", password, host, port);
  }
}
```

When I compiled and looked at generated-sources the result is:

```
@Generated("io.dinject.generator")
public class RedisConfig$di  {

  public static void build(Builder builder) {
    if (builder.isAddBeanFor(RedisConfig.class)) {
      RedisConfig bean = new RedisConfig();
      builder.register(bean, null, Data.class);
    }
  }

}
```

The class files are:

```
import io.github.cdimascio.dotenv.Dotenv;
import javax.inject.Singleton;

@Singleton
public class RedisConfig {
  private static final Dotenv dotenv = Dotenv.load();
  private final String host;
  private final int port;
  private final String password;
  private final String uri;

  public RedisConfig() {
    this.host = dotenv.get("REDIS_HOST", "localhost");
    this.port = Integer.parseInt(dotenv.get("REDIS_PORT", "6379"));
    this.password = dotenv.get("REDIS_PASSWORD", "");
    this.uri = String.format("redis://%s@%s:%s", this.password, this.host, this.port);
  }
 // getter, setter, ...
```

```
public class RedisConfig$di {
  public RedisConfig$di() {
  }

  public static void build(Builder builder) {
    if (builder.isAddBeanFor(RedisConfig.class)) {
      RedisConfig bean = new RedisConfig();
      builder.register(bean, (String)null, new Class[]{Data.class});
    }

  }
}
```

When I de-lombok the class, everything works fine. Any clues?

**Comment by rbygrave** [comment]
Can you create a failing test case?  Provide an example application that shows the error?
Thanks.

**Comment by rbygrave** [comment]
Also can you include the full stack trace and clarify if that occurs at build time?  
If using maven have you done a build using the `-X ` debug option?
Plus I think this should really be a new issue assuming you can provide a failing test case.

Thanks, Rob.

**Comment by rbygrave** [comment]
@aletundo  ... see https://github.com/dinject/dinject/issues/40

**Comment by aletundo** [comment]
@rbygrave I'm so sorry for the late reply but I was really busy at work.
I just saw the changes within the release page of the website and than I landed here!
Thanks for the fix, I'm going to use it now.

**Comment by rbygrave** [comment]
All good :)

Note that at this stage I plan to release a 2.1 version of dinject ... with the only change being that the annotations have been moved to `io.dinject.annotation` package (in a separate module).
